# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target LuaAPIStatic
ADD_LIBRARY(LuaAPIStatic STATIC IMPORTED)

# Create imported target API
ADD_LIBRARY(API SHARED IMPORTED)

# Create imported target APIStatic
ADD_LIBRARY(APIStatic STATIC IMPORTED)

# Create imported target CANDLL
ADD_LIBRARY(CANDLL SHARED IMPORTED)

# Create imported target CANDLLStatic
ADD_LIBRARY(CANDLLStatic STATIC IMPORTED)

# Create imported target I2CDLL
ADD_LIBRARY(I2CDLL SHARED IMPORTED)

# Create imported target I2CDLLStatic
ADD_LIBRARY(I2CDLLStatic STATIC IMPORTED)

# Create imported target SPIDLL
ADD_LIBRARY(SPIDLL SHARED IMPORTED)

# Create imported target SPIDLLStatic
ADD_LIBRARY(SPIDLLStatic STATIC IMPORTED)

# Create imported target RenesasDLL
ADD_LIBRARY(RenesasDLL SHARED IMPORTED)

# Create imported target RenesasDLLStatic
ADD_LIBRARY(RenesasDLLStatic STATIC IMPORTED)

# Create imported target DIODLL
ADD_LIBRARY(DIODLL SHARED IMPORTED)

# Create imported target DIODLLStatic
ADD_LIBRARY(DIODLLStatic STATIC IMPORTED)

# Create imported target TestsystemDLL
ADD_LIBRARY(TestsystemDLL SHARED IMPORTED)

# Create imported target TestsystemDLLStatic
ADD_LIBRARY(TestsystemDLLStatic STATIC IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/anagateapi-targets-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
